server:
  port: 8100

spring:
  application:
    name: order-ribbon
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public

ribbon:
  eager-load:
    # 开启懒加载
    enabled: true
    # 指定需要加载负载均衡的服务
    clients: stock-service